MVCProject/Controllers/ContentController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFrameWork;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProject.Controllers
{
    public class ContentController : Controller
    {
        ContentManager cm = new ContentManager(new EFContentDal());
        HeadingManager hm=new HeadingManager(new EFHeadingDal());
        WriterManager wm = new WriterManager(new EFWriterDal());
        public ActionResult Index()
        {
            List<Content> result = cm.GetList();
            return View(result);
        }
        public ActionResult GetByHeading(int id)
        {
            var content=cm.GetByHeading(id);
            return View(content);
        }
        [HttpGet]
        public ActionResult UpdateContent(int id)
        {
            List<SelectListItem> valueheading = (from x in hm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.HeadingName,
                                                      Value = x.HeadingId.ToString()
                                                  }
                                               ).ToList();
            List<SelectListItem> valuewriter = (from x in wm.GetList()
                                                select new SelectListItem
                                                {
                                                    Text = x.WriterName + " " + x.WriterSurname,
                                                    Value = x.WriterID.ToString()
                                                }
                                              ).ToList();
            ViewBag.vlc = valueheading;
            ViewBag.vlw = valuewriter;
            var content = cm.GetById(id);
            return View(content);
        }
        [HttpPost]
        public ActionResult UpdateContent(Content content,int id)
        {
            content.ContentId = id;
            content.ContentDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            cm.ContentUpdate(content);
            return RedirectToAction("/Index");
        }
        [HttpGet]
        public ActionResult AddContent()
        {
            List<SelectListItem> valuecategory = (from x in hm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.HeadingName,
                                                      Value = x.HeadingId.ToString()
                                                  }
                                                ).ToList();
            List<SelectListItem> valuewriter = (from x in wm.GetList()
                                                select new SelectListItem
                                                {
                                                    Text = x.WriterName +" "+ x.WriterSurname,
                                                    Value = x.WriterID.ToString()
                                                }
                                              ).ToList();
            ViewBag.vlc = valuecategory;
            ViewBag.vlw = valuewriter;
            return View();
        }
        [HttpPost]
        public ActionResult AddContent(Content c)
        {
            ContentValidator validationRules = new ContentValidator();
            ValidationResult result=validationRules.Validate(c);
            c.ContentDate= DateTime.Parse(DateTime.Now.ToShortDateString());
            if (result.IsValid)
            {
                cm.AddContent(c);
                return RedirectToAction("/Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View(c);
        }
        [HttpGet]
        public ActionResult DeleteContent(int id)
        {
            var content = cm.GetById(id);
            cm.ContentDelete(content);
            return RedirectToAction("/Index");
        }
    }
}

MVCProject/Views/Content/AddContent.cshtml
@model EntityLayer.Concrete.Content
@{
    ViewBag.Title = "AddContent";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>İçerik Ekleme</h2>
<br />
@using (Html.BeginForm("AddContent", "Content", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("İçerik Adı:")
        @Html.TextBoxFor(x => x.ContentValue, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ContentValue)
        <br /><br />
        @Html.Label("İçeriğin Başlığı:")
        @Html.DropDownListFor(x => x.HeadingId, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        <br /><br />
        @Html.Label("İçeriğin Yazarı:")
        @Html.DropDownListFor(x => x.WriterId, (List<SelectListItem>)ViewBag.vlw, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Kaydet</button>
    </div>
}>

MVCProject/Views/Content/DeleteContent.cshtml
@{
    ViewBag.Title = "DeleteContent";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>DeleteContent</h2>

MVCProject/Views/Content/GetByHeading.cshtml
@using EntityLayer.Concrete
@model List<Content>
@{
    ViewBag.Title = "GetByHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">
                @foreach (var item in Model)
                {
                    <!-- Timelime example  -->
                    <div class="row">
                        <div class="col-md-12">
                            <!-- The time line -->
                            <div class="timeline">
                                <!-- timeline time label -->
                                <div class="time-label">
                                    <span class="bg-success">@item.ContentDate</span>
                                </div>
                                <!-- /.timeline-label -->
                                <!-- timeline item -->
                                <div>
                                        <i class="fas fa-comment bg-yellow"></i>
                                        <div class="timeline-item">
                                            <h3 class="timeline-header"><a href="#">@item.Writer.WriterName @item.Writer.WriterSurname</a></h3>
                                            <div class="timeline-body">
                                                @item.ContentValue
                                            </div>
                                        </div>
                                    

                                </div>
                                <!-- END timeline item -->
                            </div>
                        </div>
                        <!-- /.col -->
                    </div>
                }
                </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>

MVCProject/Views/Content/Index.cshtml
@using EntityLayer.Concrete
@model List<Content>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>İçerikler</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">İçerik İşlemleri</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                İçerik Adı
                            </th>
                            <th style="width: 30%">
                                Oluşturan Yazar
                            </th>
                            <th style="width: 8%" class="text-center">
                                Başlık
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {


                            <tr>
                                
                                <td>
                                    @item.ContentId
                                </td>
                                <td>
                                    <a>
                                        @item.ContentValue
                                    </a>
                                    <br />
                                    <small>
                                        @item.ContentDate
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="~/AdminLTE-3.0.4/dist/img/avatar.png">
                                        </li>
                                    </ul>
                                </td>
                                <td class="project-state">
                                    <span >@item.Heading.HeadingName</span>
                                </td>
                                <td class="project-actions text-right">                                    
                                    <a class="btn btn-info btn-sm" href="~/Content/UpdateContent/@item.ContentId">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="~/Content/DeleteContent/@item.ContentId">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
            <br />
        </div>
        <a href="~/Content/AddContent" class="btn btn-success">Yeni İçerik Ekle</a>
        <br />
        <!-- /.card -->
    </section>
</body>
</html>

MVCProject/Views/Content/UpdateContent.cshtml
@model EntityLayer.Concrete.Content
@{
    ViewBag.Title = "UpdateContent";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h2>İçerik Düzenleme</h2>
<br />
@using (Html.BeginForm("UpdateContent", "Content", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("İçerik Adı:")
        @Html.TextBoxFor(x => x.ContentValue, new { @class = "form-control" })
        <br /><br />
        @Html.Label("İçeriğin Başlığı:")
        @Html.DropDownListFor(x => x.HeadingId, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        <br /><br />
        @Html.Label("Başlığın Yazarı:")
        @Html.DropDownListFor(x => x.WriterId, (List<SelectListItem>)ViewBag.vlw, new { @class = "form-control" })
        <br />
        <button class="btn btn-warning">Kaydet</button>
    </div>
}>