MVCProject/Controllers/HeadingController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFrameWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProject.Controllers
{
    public class HeadingController : Controller
    {
        HeadingManager hm = new HeadingManager(new EFHeadingDal());
        public ActionResult Index()
        {
            var headings = hm.GetList();
            return View();
        }
        [HttpGet]
        public ActionResult GetByHeading(int id)
        {
            var headings = hm.GetByWriterId(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult GetByCategory(int id)
        {
            var categories = hm.GetByCategoryId(id);
            return View(categories);
        }
    }
}

MVCProject/Views/Heading/AddHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "AddHeading";
}
<h2>Yeni Başlık Ekleme</h2>
<br />
@using (Html.BeginForm("AddHeading", "Heading", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Başlık Adı:")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)
        <br /><br />
        @Html.Label("Başlık Tarihi:")
        @Html.TextBoxFor(x => x.HeadingDate, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingDate)        
        <br /><br />
        @Html.Label("Başlığın Kategorisi:")
        @Html.DropDownListFor(x=>x.CategoryId,(List<SelectListItem>)ViewBag.vlc,new {@class="form-control"})
        <br /><br />
        @Html.Label("Başlığın Yazarı:")
        @Html.DropDownListFor(x=>x.WriterId,(List<SelectListItem>)ViewBag.vlw,new{@class="form-control"} )
        <br />
        <div class="input-group date" data-provide="datepicker">
            <input type="text" class="form-control" />
            <div class="input-group-addon">
                <span class="glyphicon glyphicon-th"></span>
            </div>
        </div>
        <button class="btn btn-warning">Kaydet</button>
    </div>
}>

MVCProject/Views/Heading/EditHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>EditHeading</h2>

@using (Html.BeginForm("EditHeading", "Heading", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Başlık Adı:")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)
        <br /><br />
        @Html.Label("Başlık Tarihi:")
        @Html.TextBoxFor(x => x.HeadingDate, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingDate)
        <br /><br />
        @Html.Label("Başlığın Kategorisi:")
        @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        <br /><br />
        @Html.Label("Başlığın Yazarı:")
        @Html.DropDownListFor(x => x.WriterId, (List<SelectListItem>)ViewBag.vlw, new { @class = "form-control" })
        <br />
        <button class="btn btn-warning">Kaydet</button>
    </div>
}>

MVCProject/Views/Heading/GetByCategory.cshtml
@using EntityLayer.Concrete
@model List<Heading>
@{
    ViewBag.Title = "GetByCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h2>Başlıklar</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Ad</th>
        <th>Tarih</th>
        <th>Kategori Id</th>
        <th>Yazar Id</th>
    </tr>
    @foreach (var items in Model)
    {
        <tr>
            <td>@items.HeadingId</td>
            <td>@items.HeadingName</td>
            <td>@items.HeadingDate</td>
            <td>@items.CategoryId</td>
            <td>@items.WriterId</td>
        </tr>
    }
</table>
<br />

MVCProject/Views/Heading/GetByHeading.cshtml
@using EntityLayer.Concrete
@model List<Heading>
@{
    ViewBag.Title = "GetByHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Başlıklar</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Ad</th>
        <th>Tarih</th>
        <th>Kategori Id</th>
        <th>Yazar Id</th>
    </tr>
    @foreach (var items in Model)
    {
        <tr>
            <td>@items.HeadingId</td>
            <td>@items.HeadingName</td>
            <td>@items.HeadingDate</td>
            <td>@items.CategoryId</td>
            <td>@items.WriterId</td>
        </tr>
    }
</table>
<br />

MVCProject/Views/Heading/Index.cshtml
@using EntityLayer.Concrete
@model List<Heading>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Başlıklar</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Ad</th>
        <th>Tarih</th>
        <th>Kategori Id</th>
        <th>Yazar Id</th>
    </tr>
    @foreach (var items in Model)
    {
        <tr>
            <td>@items.HeadingId</td>
            <td>@items.HeadingName</td>
            <td>@items.HeadingDate</td>
            <td>@items.CategoryId</td>
            <td>@items.WriterId</td>
        </tr>
    }
</table>
<br />